INSERT INTO HistoricoMundiales (AñoMundial, PaisOrganizador, PaisCampeon, Goles, Goleador, NacionalidadGoleador, Arquero, NacionalidadArquero, Mascota) VALUES 
('1930-01-01','Uruguay','Uruguay',70,'Guillermo Stábile','Argentina','Enrique Ballesteros','Uruguay',NULL),
('1934-01-01','Italia','Italia',77,'Oldřich Nejedlý','Checoslovaquia','Gianpiero Combi','Italia',NULL),
('1938-01-01','Francia','Italia',84,'Leónidas da Silva','Brasil','František Plánička','Checoslovaquia',NULL),
('1950-01-01','Brasil','Uruguay',254,'Ademir Marques de Menezes','Brasil','Roque Máspoli','Uruguay',NULL),
('1954-01-01','Suiza','Alemania Federal',254,'Sándor Kocsis','Hungría','Sepp Maier','Alemania Federal','Fritz'),
('1958-01-01','Suecia','Brasil',126,'Pelé','Brasil','Gilmar','Brasil',NULL),
('1962-01-01','Chile','Brasil',89,'Vavá','Brasil','Viliam Schrojf','Checoslovaquia','Rambler'),
('1966-01-01','Inglaterra','Inglaterra',98,'Geoff Hurst','Inglaterra','Gordon Banks','Inglaterra','Willie'),
('1970-01-01','México','Brasil',95,'Gerd Müller','Alemania Federal','Ladislao Mazurkiewicz','Uruguay','Juanito'),
('1974-01-01','Alemania Federal','Alemania Federal',237,'Grzegorz Lato','Polonia','Sepp Maier','Alemania Federal','Tip y Tap'),
('1978-01-01','Argentina','Argentina',245,'Mario Kempes','Argentina','Ubaldo Fillol','Argentina','Gauchito'),
('1982-01-01','España','Italia',146,'Paolo Rossi','Italia','Dino Zoff','Italia','Naranjito'),
('1986-01-01','México','Argentina',132,'Diego Maradona','Argentina','Harald Schumacher','Alemania Federal','Pique'),
('1990-01-01','Italia','Alemania Federal',165,'Salvatore Schillaci','Italia','Sergio Goycochea','Argentina','Ciao'),
('1994-01-01','Estados Unidos','Brasil',141,'Romário','Brasil','Claudio Taffarel','Brasil','Striker'),
('1998-01-01','Francia','Francia',171,'Davor Šuker','Croacia','Fabien Barthez','Francia','Footix'),
('2002-01-01','Corea del Sur y Japón','Brasil',184,'Ronaldo','Brasil','Oliver Kahn','Alemania','Nikko'),
('2006-01-01','Alemania','Italia',147,'Miroslav Klose','Alemania','Gianluigi Buffon','Italia','Goleo VI'),
('2010-01-01','Sudáfrica','España',147,'Thomas Müller','Alemania','Iker Casillas','España','Zakumi'),
('2014-01-01','Brasil','Alemania',171,'James Rodríguez','Colombia','Manuel Neuer','Alemania','Fuleco'),
('2018-01-01','Rusia','Francia',169,'Harry Kane','Inglaterra','Thibaut Courtois','Bélgica','Zabivaka'),
('2022-01-01','Qatar','Argentina',254,'Kylian Mbappé','Francia','Emiliano Martínez','Argentina','Laeeb');
